# Generated by Django 2.0.6 on 2019-03-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizEval', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='user_text',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_id',
            field=models.IntegerField(default=0),
        ),
    ]
