# Generated by Django 2.0.6 on 2019-03-03 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizEval', '0002_auto_20190303_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_i', models.CharField(max_length=15)),
                ('estID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizEval.estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='submition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
                ('submit_date', models.DateTimeField(auto_now=True, verbose_name='date submit')),
                ('estID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizEval.estudiantes')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='submit_date',
        ),
        migrations.AddField(
            model_name='quiz',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Create Date'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='good_answer',
            field=models.CharField(default='[]', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_description',
            field=models.CharField(default=2, max_length=400),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='submition',
            name='quizID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizEval.Quiz'),
        ),
        migrations.AddField(
            model_name='keys',
            name='quizID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizEval.Quiz'),
        ),
    ]
